
class StaticData {

    static getSource(id){
        return this.sources.find( ({ SOURCE }) => SOURCE === id );
    }
    
    // list of urls of Andrej Babis
    static babisSites = [
        {"URL":"5plus2.cz"},
        {"URL":"Acomware.cz"},
        {"URL":"AkcniCeny.cz"},
        {"URL":"almanachy.sk"},
        {"URL":"Arome.cz"},
        {"URL":"Bazaar.cz"},
        {"URL":"Dolcevita.cz"},
        {"URL":"emimino.cz"},
        {"URL":"expres.cz"},
        {"URL":"HNonline.sk"},
        {"URL":"idnes.cz"},
        {"URL":"impuls.cz"},
        {"URL":"JenProHolky.cz"},
        {"URL":"JenProMuze.cz"},
        {"URL":"jenprozeny.cz"},
        {"URL":"lidovky.cz"},
        {"URL":"mafra.cz"},
        {"URL":"mafra.sk"},
        {"URL":"metro.cz"},
        {"URL":"mobil.cz"},
        {"URL":"ocko.tv"},
        {"URL":"Portmonka.cz"},
        {"URL":"rockzone.cz"},
        {"URL":"rajce.net"},
        {"URL":"svetevity.sk"},
        {"URL":"Televize.cz"},
        {"URL":"VratnePenize.cz"},
        {"URL":"1hradecka.navos-km.cz"},
        {"URL":"achplv.sk"},
        {"URL":"afeed.cz"},
        {"URL":"agroprim.cz"},
        {"URL":"agrokacice.cz"},
        {"URL":"agffoodlogistics.cz"},
        {"URL":"agrics.cz"},
        {"URL":"agrics.sk"},
        {"URL":"agd-jevisovice.cz"},
        {"URL":"zdjinin.cz"},
        {"URL":"agromikulovice.navos-km.cz"},
        {"URL":"agroplchov.cz"},
        {"URL":"agropresovice.navos-km.cz"},
        {"URL":"agrorozsochy.cz"},
        {"URL":"agrovnorovy.navos-km.cz"},
        {"URL":"agrobech.cz"},
        {"URL":"agrobor.cz"},
        {"URL":"agrocomhrusovany.cz"},
        {"URL":"agrofert.de"},
        {"URL":"agrofertpolska.navos-km.cz"},
        {"URL":"agrofert.cz"},
        {"URL":"agroparkl.navos-km.cz"},
        {"URL":"agptt.sk"},
        {"URL":"agropodnik.eu"},
        {"URL":"ap-hodonin.cz"},
        {"URL":"agrotec.cz"},
        {"URL":"agrotecservis.cz"},
        {"URL":"agrotechnicmoravia.cz"},
        {"URL":"agrozes.cz"},
        {"URL":"agrozzn.cz"},
        {"URL":"agsagro.cz"},
        {"URL":"alimex-as.cz"},
        {"URL":"animalco.cz"},
        {"URL":"animo-zatec.cz"},
        {"URL":"agrofert.cz"},
        {"URL":"arbo-kt.cz"},
        {"URL":"clcekanice.cz"},
        {"URL":"cocltd.cz/en/"},
        {"URL":"cerea.cz"},
        {"URL":"ceressuto.hu"},
        {"URL":"ceskavejce.cz"},
        {"URL":"cvfarms.cz"},
        {"URL":"devagro.hu/en/"},
        {"URL":"deza.cz"},
        {"URL":"doubravicka.navos-km.cz"},
        {"URL":"drukostrizov.cz"},
        {"URL":"duslo.sk"},
        {"URL":"dzvnova-as.cz"},
        {"URL":"ethanolenergy.cz"},
        {"URL":"farmaholesov.navos-km.cz"},
        {"URL":"farmtec.cz"},
        {"URL":"fatra.cz"},
        {"URL":"greenchem-adblue.com"},
        {"URL":"hyza.sk"},
        {"URL":"ikragrar.hu"},
        {"URL":"jave-pork.cz"},
        {"URL":"kvarto.cz"},
        {"URL":"kladrubska.cz"},
        {"URL":"kmotr.cz"},
        {"URL":"kosteleckeuzeniny.cz"},
        {"URL":"krahulik.cz"},
        {"URL":"lieken.de"},
        {"URL":"liprapork.cz"},
        {"URL":"impuls.cz"},
        {"URL":"lovochemie.cz"},
        {"URL":"luzanskazemedelska.cz"},
        {"URL":"m-a-j.cz"},
        {"URL":"mafraslovakia.hnonline.sk/"},
        {"URL":"mafra.cz"},
        {"URL":"mavex-agro.cz"},
        {"URL":"tatramleko.cz"},
        {"URL":"nadace-agrofert.cz"},
        {"URL":"navosfarmtechnic.cz"},
        {"URL":"navos-km.cz"},
        {"URL":"novydvur.navos-km.cz"},
        {"URL":"ntkft.hu"},
        {"URL":"odbytovcary.cz"},
        {"URL":"olma.cz"},
        {"URL":"osevaagri.cz"},
        {"URL":"oseva.eu"},
        {"URL":"papei.cz"},
        {"URL":"pekarnazelenalouka.cz"},
        {"URL":"penam.sk"},
        {"URL":"penam.cz"},
        {"URL":"prochazka.cz"},
        {"URL":"podchribijezov.navos-km.cz"},
        {"URL":"podebradskablata.cz"},
        {"URL":"precheza.cz"},
        {"URL":"preolfood.cz"},
        {"URL":"preol.cz"},
        {"URL":"primagra.cz"},
        {"URL":"profrost.cz"},
        {"URL":"1zatecka.cz"},
        {"URL":"pzz.cz"},
        {"URL":"rknaklo.navos-km.cz"},
        {"URL":"sadycz.cz"},
        {"URL":"schromfarms.cz"},
        {"URL":"skwp.de"},
        {"URL":"spvpel.cz"},
        {"URL":"statekbrezany.navos-km.cz"},
        {"URL":"stateklom.cz"},
        {"URL":"synthesia.eu"},
        {"URL":"tajba.sk"},
        {"URL":"vejprniceenergo.cz"},
        {"URL":"vlcnovskazemedelska.cz"},
        {"URL":"vodnanskadrubez.cz"},
        {"URL":"vodnanske-kure.cz"},
        {"URL":"vsv.navos-km.cz"},
        {"URL":"vucht.sk"},
        {"URL":"vykrmtagrea.cz"},
        {"URL":"vykrmtrebic.cz"},
        {"URL":"vuos.com"},
        {"URL":"wotanforest.cz"},
        {"URL":"zaspodchotuci.cz"},
        {"URL":"zastavmezlodeje.cz"},
        {"URL":"zdkrechor.cz"},
        {"URL":"zeasmancice.cz"},
        {"URL":"zeaspuclice.cz"},
        {"URL":"zem.cz"},
        {"URL":"zosonomysl.cz"},
        {"URL":"zsblsany.cz"},
        {"URL":"zstrebivlice.cz"},
        {"URL":"zemos.navos-km.cz"},
        {"URL":"zemspol.navos-km.cz"},
        {"URL":"zeosbrnirov.cz"},
        {"URL":"zeraratiskovice.cz"},
        {"URL":"zevachl.cz"},
        {"URL":"zlaty-klas.cz"},
        {"URL":"zodzalabi.cz"},
        {"URL":"zosbesno.cz"},
        {"URL":"zs-vilemov.cz"},
        {"URL":"zsvysocina.cz"},
        {"URL":"zznpe.cz"},
        {"URL":"zznpolabi.cz"}
    ];

    // list of untruested urls
    static untrustedSites = [

        {"ID":"1", "URL":"ac24.cz", "SOURCE":"1,2,3,4,5,6"},
        {"ID":"2", "URL":"aeronet.cz", "SOURCE":"1,2,3,4,5,6"},
        {"ID":"3", "URL":"afinabul.blog.cz", "SOURCE":"1,3"},
        {"ID":"4", "URL":"aktuality24.sk", "SOURCE":"1"},
        {"ID":"5", "URL":"almanach.cz", "SOURCE":"2,6"},
        {"ID":"6", "URL":"alternativnimagazin.cz", "SOURCE":"1"},
        {"ID":"7", "URL":"alternews.cz", "SOURCE":"3"},
        {"ID":"8", "URL":"antiilluminati.net", "SOURCE":"2,6"},
        {"ID":"9", "URL":"anti-illuminati.wbl.sk", "SOURCE":"1"},
        {"ID":"10", "URL":"arfa.cz", "SOURCE":"1"},
        {"ID":"11", "URL":"arindrexler.com", "SOURCE":"1"},
        {"ID":"12", "URL":"auria.sk", "SOURCE":"3"},
        {"ID":"13", "URL":"babickinerady.sk", "SOURCE":"1"},
        {"ID":"14", "URL":"badatel.net", "SOURCE":"1,3"},
        {"ID":"15", "URL":"badatel.sk", "SOURCE":"3"},
        {"ID":"16", "URL":"bajecnezdravie.sk", "SOURCE":"1"},
        {"ID":"17", "URL":"bajecnezeny.sk", "SOURCE":"1"},
        {"ID":"18", "URL":"bajecnylekar.cz", "SOURCE":"1"},
        {"ID":"19", "URL":"bajecnylekar.sk", "SOURCE":"1"},
        {"ID":"20", "URL":"bajecnyzivot.sk", "SOURCE":"1"},
        {"ID":"21", "URL":"beo.sk", "SOURCE":"3"},
        {"ID":"22", "URL":"bezpolitickekorektnosti.cz", "SOURCE":"1,2,3,4,6"},
        {"ID":"23", "URL":"biblik.sk", "SOURCE":"1"},
        {"ID":"24", "URL":"biosferaklub.info", "SOURCE":"1"},
        {"ID":"25", "URL":"blokprotiislamizaci.cz", "SOURCE":"1"},
        {"ID":"26", "URL":"bnw-nwo.wz.cz", "SOURCE":"1"},
        {"ID":"27", "URL":"borea.cz", "SOURCE":"4"},
        {"ID":"28", "URL":"BORREA.EU", "SOURCE":"4"},
        {"ID":"29", "URL":"breitbart.com", "SOURCE":"1"},
        {"ID":"30", "URL":"casopis-sifra.cz", "SOURCE":"1,2,6"},
        {"ID":"31", "URL":"casopisargument.cz", "SOURCE":"8"},
        {"ID":"32", "URL":"ceskoaktualne.cz", "SOURCE":"1,2"},
        {"ID":"33", "URL":"ceskozdrave.cz", "SOURCE":"1"},
        {"ID":"35", "URL":"cestacloveka.sk", "SOURCE":"1"},
        {"ID":"36", "URL":"cestyksobe.cz", "SOURCE":"1,6"},
        {"ID":"37", "URL":"cez-okno.net", "SOURCE":"3"},
        {"ID":"38", "URL":"conspi.cz", "SOURCE":"1"},
        {"ID":"39", "URL":"ctusi.info", "SOURCE":"2"},
        {"ID":"40", "URL":"czech.ruvr.ru", "SOURCE":"3"},
        {"ID":"41", "URL":"czechfreepress.cz", "SOURCE":"1,2,3,4,6"},
        {"ID":"42", "URL":"datel.sk", "SOURCE":"1"},
        {"ID":"43", "URL":"davdva.sk", "SOURCE":"1"},
        {"ID":"44", "URL":"dennikpolitika.sk", "SOURCE":"1"},
        {"ID":"46", "URL":"dobajedu.cz", "SOURCE":"1"},
        {"ID":"47", "URL":"dolezite.sk", "SOURCE":"1,3"},
        {"ID":"48", "URL":"domacaliecba.sk", "SOURCE":"1"},
        {"ID":"49", "URL":"drsne.sk", "SOURCE":"1"},
        {"ID":"50", "URL":"dt24.cz", "SOURCE":"1"},
        {"ID":"51", "URL":"e-republika.cz", "SOURCE":"1,2,6"},
        {"ID":"52", "URL":"eiaktivity.sk", "SOURCE":"3"},
        {"ID":"53", "URL":"energieupramene.blogspot.sk", "SOURCE":"1"},
        {"ID":"55", "URL":"eportal.cz", "SOURCE":"1,2,6"},
        {"ID":"56", "URL":"ers.blog.cz", "SOURCE":"1"},
        {"ID":"57", "URL":"eurabia.cz", "SOURCE":"1"},
        {"ID":"58", "URL":"eurasia24.cz", "SOURCE":"1,2,6"},
        {"ID":"59", "URL":"euroasie.info", "SOURCE":"1"},
        {"ID":"60", "URL":"Eurodenik.cz", "SOURCE":"1,4"},
        {"ID":"61", "URL":"euronoviny.eu", "SOURCE":"1"},
        {"ID":"62", "URL":"eurorespekt.sk", "SOURCE":"1"},
        {"ID":"63", "URL":"euportal.cz", "SOURCE":"1,2,4,6"},
        {"ID":"64", "URL":"euserver.cz", "SOURCE":"1,2,4,6"},
        {"ID":"65", "URL":"exopolitika.cz", "SOURCE":"1"},
        {"ID":"66", "URL":"extraplus.sk", "SOURCE":"1"},
        {"ID":"67", "URL":"farmazdravi.cz", "SOURCE":"1"},
        {"ID":"68", "URL":"freedomeurope.eu", "SOURCE":"1"},
        {"ID":"69", "URL":"freeglobe.cz", "SOURCE":"1,2,4,6"},
        {"ID":"70", "URL":"freepub.cz", "SOURCE":"1,3"},
        {"ID":"71", "URL":"fresher.sk", "SOURCE":"1"},
        {"ID":"72", "URL":"gloria.tv", "SOURCE":"1"},
        {"ID":"73", "URL":"halonoviny.com", "SOURCE":"1"},
        {"ID":"74", "URL":"hlavnespravy.sk", "SOURCE":"3"},
        {"ID":"75", "URL":"hlavnydennik.sk", "SOURCE":"1"},
        {"ID":"76", "URL":"hrot.info", "SOURCE":"1"},
        {"ID":"77", "URL":"idemvolit.sk", "SOURCE":"1"},
        {"ID":"78", "URL":"inespravy.sk", "SOURCE":"3"},
        {"ID":"79", "URL":"infokuryr.cz", "SOURCE":"1,2,4,6"},
        {"ID":"80", "URL":"infovojna.sk", "SOURCE":"1"},
        {"ID":"81", "URL":"infowars.cz", "SOURCE":"2,6"},
        {"ID":"82", "URL":"ipribeh.cz", "SOURCE":"1"},
        {"ID":"83", "URL":"instory.cz", "SOURCE":"5"},
        {"ID":"84", "URL":"isstras.eu", "SOURCE":"1,2,4,6"},
        {"ID":"85", "URL":"je-to-inak.livejournal.com", "SOURCE":"1"},
        {"ID":"86", "URL":"jenona.tiscali.cz", "SOURCE":"1"},
        {"ID":"87", "URL":"lajkit.cz", "SOURCE":"1,2,4,6"},
        {"ID":"88", "URL":"legalizuj.to", "SOURCE":"1"},
        {"ID":"89", "URL":"leva-net.webnode.cz", "SOURCE":"1"},
        {"ID":"90", "URL":"lifenews.sk", "SOURCE":"1"},
        {"ID":"91", "URL":"lucasperny.blog.pravda.sk", "SOURCE":"1"},
        {"ID":"92", "URL":"karolinaloskotova.blog.cz", "SOURCE":"1"},
        {"ID":"93", "URL":"kulturblog.sk", "SOURCE":"1"},
        {"ID":"94", "URL":"magnificat.sk", "SOURCE":"1,3"},
        {"ID":"95", "URL":"magazin1.sk", "SOURCE":"1"},
        {"ID":"96", "URL":"mcaris.net", "SOURCE":"1"},
        {"ID":"97", "URL":"medicalcentrum.eu", "SOURCE":"1"},
        {"ID":"98", "URL":"medzicas.sk", "SOURCE":"1"},
        {"ID":"99", "URL":"megazine.cz", "SOURCE":"1,2,6"},
        {"ID":"100", "URL":"mikan.cz", "SOURCE":"2,6"},
        {"ID":"101", "URL":"mocvedomi.cz", "SOURCE":"1"},
        {"ID":"102", "URL":"mysteria.sk", "SOURCE":"1"},
        {"ID":"103", "URL":"nadhlad.com", "SOURCE":"1,3"},
        
        {"ID":"104", "URL":"nadlani.org", "SOURCE":"1"},
        {"ID":"105", "URL":"napalete.sk", "SOURCE":"1"},
        {"ID":"106", "URL":"narodninoviny.cz", "SOURCE":"1"},
        {"ID":"107", "URL":"naturalnews.com", "SOURCE":"1"},
        {"ID":"108", "URL":"nazorobcana.sk", "SOURCE":"1,3"},
        {"ID":"109", "URL":"necenzurovane.net", "SOURCE":"1"},
        {"ID":"110", "URL":"nejhorsi.cz", "SOURCE":"1"},
        {"ID":"111", "URL":"nejvic-info.cz", "SOURCE":"1"},
        {"ID":"112", "URL":"nekorektni-tv.cz", "SOURCE":"1"},
        {"ID":"113", "URL":"nemesis.sk", "SOURCE":"1"},
        {"ID":"114", "URL":"neskutocne.sk", "SOURCE":"3"},
        {"ID":"115", "URL":"netky.sk", "SOURCE":"1"},
        {"ID":"117", "URL":"novarepublika.cz", "SOURCE":"1,2,6"},
        {"ID":"118", "URL":"nwoo.org", "SOURCE":"1,2,3,4,6"},
        {"ID":"119", "URL":"obcianskytribunal.sk", "SOURCE":"1,3"},
        {"ID":"120", "URL":"onlineslecna.sk", "SOURCE":"1"},
        {"ID":"121", "URL":"orgo-net.blogspot", "SOURCE":"1,2,3,4,6"},
        {"ID":"122", "URL":"osud.cz", "SOURCE":"1,2,3,4,6"},
        {"ID":"123", "URL":"otevrisvoumysl.cz", "SOURCE":"1"},
        {"ID":"124", "URL":"otvoroci.com", "SOURCE":"1"},
        {"ID":"125", "URL":"outsidermedia.cz", "SOURCE":"1"},
        {"ID":"126", "URL":"ozonyx.cz", "SOURCE":"1"},
        {"ID":"127", "URL":"panobcan.sk", "SOURCE":"1,3"},
        {"ID":"128", "URL":"paratdnes.cz", "SOURCE":"1,2,6"},
        {"ID":"129", "URL":"parlamentne-volby-2016.sk", "SOURCE":"1"},
        {"ID":"130", "URL":"parlamentnilisty.cz", "SOURCE":"2,4,5,6"},
        {"ID":"131", "URL":"picuscapital.sk", "SOURCE":"1"},
        {"ID":"132", "URL":"planetajednoduchost.sk", "SOURCE":"1"},
        {"ID":"133", "URL":"pokec24.cz", "SOURCE":"1"},
        {"ID":"134", "URL":"politickemimovladky.sk", "SOURCE":"1"},
        {"ID":"135", "URL":"pravdive.eu", "SOURCE":"1,2,3,6"},
        {"ID":"136", "URL":"pravyprostor.cz", "SOURCE":"1"},
        {"ID":"137", "URL":"precitaj.si", "SOURCE":"1"},
        {"ID":"138", "URL":"prehladsprav.sk", "SOURCE":"1"},
        {"ID":"139", "URL":"presstv.sk", "SOURCE":"1"},
        {"ID":"140", "URL":"priezor.com", "SOURCE":"1"},
        {"ID":"141", "URL":"priznakytransformace.cz", "SOURCE":"1"},
        {"ID":"142", "URL":"procproto.cz", "SOURCE":"1"},
        {"ID":"143", "URL":"proevropu.com", "SOURCE":"1"},
        {"ID":"144", "URL":"prosvet.cz", "SOURCE":"1"},
        {"ID":"145", "URL":"protiproud.cz", "SOURCE":"1,2,4,5,6"},
        {"ID":"146", "URL":"protiprud.sk", "SOURCE":"1"},
        {"ID":"147", "URL":"protiprudu.org", "SOURCE":"1,3"},
        {"ID":"148", "URL":"prvnizpravy.cz", "SOURCE":"1,2,6"},
        {"ID":"149", "URL":"prvopodstata.blog.cz", "SOURCE":"6"},
        {"ID":"150", "URL":"prvopodstata.com", "SOURCE":"1,2,6"},
        {"ID":"151", "URL":"radynadzlato.sk", "SOURCE":"1"},
        {"ID":"152", "URL":"radyprezdravie.sk", "SOURCE":"1"},
        {"ID":"153", "URL":"radyprezeny.sk", "SOURCE":"1"},
        {"ID":"154", "URL":"radyzdravie.sk", "SOURCE":"1"},
        {"ID":"155", "URL":"resso.sk", "SOURCE":"1"},
        {"ID":"156", "URL":"rodinajezaklad.sk", "SOURCE":"3"},
        {"ID":"157", "URL":"rozhladna.org", "SOURCE":"1"},
        {"ID":"158", "URL":"rudovasky.com", "SOURCE":"1"},
        {"ID":"159", "URL":"rukojmi.cz", "SOURCE":"1,2,4,6"},
        {"ID":"160", "URL":"sho.sk", "SOURCE":"3"},
        {"ID":"161", "URL":"silavedomia.sk", "SOURCE":"1"},
        {"ID":"162", "URL":"Skrytapravda.cz", "SOURCE":"1,4"},
        {"ID":"163", "URL":"slobodavockovani.sk", "SOURCE":"1"},
        {"ID":"164", "URL":"slobodnyvyber.sk", "SOURCE":"1"},
        {"ID":"165", "URL":"slobodnyvysielac.sk", "SOURCE":"1"},
        {"ID":"166", "URL":"slovak.ruvr.ru", "SOURCE":"3"},
        {"ID":"167", "URL":"slovakexportregister.eu", "SOURCE":"1"},
        {"ID":"168", "URL":"slovenskeslovo.sk", "SOURCE":"1,3"},
        {"ID":"169", "URL":"Smartnews.cz", "SOURCE":"4"},
        {"ID":"170", "URL":"spravodaj.net", "SOURCE":"1"},
        {"ID":"171", "URL":"sptnkne.ws", "SOURCE":"1,2,5,6"},
        {"ID":"172", "URL":"sputniknews.com", "SOURCE":"1,2,5,6"},
        {"ID":"173", "URL":"Stalo-se.cz", "SOURCE":"1,4"},
        {"ID":"174", "URL":"stopislam.eu", "SOURCE":"1"},
        {"ID":"175", "URL":"stratenaeuropa.sk", "SOURCE":"1"},
        {"ID":"176", "URL":"suenee.cz", "SOURCE":"1"},
        {"ID":"177", "URL":"svetkolemnas.info", "SOURCE":"1,2,3,4,6"},
        {"ID":"178", "URL":"svobodnenoviny.eu", "SOURCE":"1,2,3,4,6"},
        {"ID":"179", "URL":"svobodnymonitor.cz", "SOURCE":"1"},
        {"ID":"180", "URL":"vaseforum.sk", "SOURCE":"3"},
        {"ID":"181", "URL":"veksvetla.cz", "SOURCE":"1"},
        {"ID":"182", "URL":"venuska.cz", "SOURCE":"1"},
        {"ID":"183", "URL":"vigilantcitizen.com", "SOURCE":"1"},
        {"ID":"184", "URL":"VINEGRET.CZ", "SOURCE":"4"},
        {"ID":"185", "URL":"vipnoviny.cz", "SOURCE":"1"},
        {"ID":"186", "URL":"vkpatriarhat.org", "SOURCE":"3"},
        {"ID":"187", "URL":"vlasteneckenoviny.cz", "SOURCE":"1,2,4,6"},
        {"ID":"188", "URL":"vlastnihlavou.cz", "SOURCE":"2,3,6"},
        {"ID":"189", "URL":"voxvictims.com", "SOURCE":"3"},
        {"ID":"190", "URL":"sho.sk", "SOURCE":"1"},
        {"ID":"192", "URL":"slobodnyvysielac.sk", "SOURCE":"3"},
        {"ID":"193", "URL":"southfront.org", "SOURCE":"1"},
        {"ID":"194", "URL":"spolocnostsbm.com", "SOURCE":"3"},
        {"ID":"195", "URL":"stopautogenocide.sk", "SOURCE":"3"},
        {"ID":"196", "URL":"stredoevropan.cz", "SOURCE":"1"},
        {"ID":"197", "URL":"tadesco.cz", "SOURCE":"1"},
        {"ID":"198", "URL":"tadesco.org", "SOURCE":"1"},
        {"ID":"199", "URL":"tartaria.sk", "SOURCE":"1"},
        {"ID":"200", "URL":"themindunleashed.com", "SOURCE":"1"},
        {"ID":"201", "URL":"trendweb.sk", "SOURCE":"1"},
        {"ID":"202", "URL":"tydenikobcanskepravo.cz", "SOURCE":"1"},
        {"ID":"203", "URL":"vedomec.com", "SOURCE":"1"},
        {"ID":"204", "URL":"vitalitis.cz", "SOURCE":"1"},
        {"ID":"205", "URL":"voxpopuliblog.cz", "SOURCE":"1"},
        
        {"ID":"206", "URL":"vylectese.cz", "SOURCE":"1"},
        {"ID":"207", "URL":"wertyzreport.cz", "SOURCE":"1"},
        {"ID":"208", "URL":"wmmagazin.cz", "SOURCE":"1"},
        {"ID":"209", "URL":"woman.tiscali.cz", "SOURCE":"1"},
        {"ID":"210", "URL":"weeks.cz", "SOURCE":"1"},
        {"ID":"211", "URL":"withform.cz", "SOURCE":"1"},
        {"ID":"212", "URL":"yournewswire.com", "SOURCE":"1"},
        {"ID":"213", "URL":"zahadnysvet.sk", "SOURCE":"1"},
        {"ID":"214", "URL":"ze-sveta.cz", "SOURCE":"3"},
        {"ID":"215", "URL":"zemavek.sk", "SOURCE":"1,3"},
        {"ID":"216", "URL":"zlapanda.cz", "SOURCE":"1"},
        {"ID":"217", "URL":"zpravodaj24.eu", "SOURCE":"1"},
        {"ID":"218", "URL":"zvedavec.org", "SOURCE":"1,2,3,4,6"},
        {"ID":"380", "URL":"artek.cz", "SOURCE":"4"},
        {"ID":"381", "URL":"youth-time.org", "SOURCE":"4"},
        {"ID":"382", "URL":"stop5g.cz", "SOURCE":"1"},
        {"ID":"383", "URL":"ezopress.sk", "SOURCE":"1"},
        {"ID":"384", "URL":"prekladyodlesa.sk", "SOURCE":"1"},
        {"ID":"385", "URL":"informace.top", "SOURCE":"1"},
        {"ID":"386", "URL":"petrabostlova.wordpress.com", "SOURCE":"1"},
        {"ID":"387", "URL":"cz24.news", "SOURCE":"1"},
        {"ID":"388", "URL":"naseveru.org", "SOURCE":"1"},
        {"ID":"389", "URL":"sk.news-front.info", "SOURCE":"1"},
        {"ID":"390", "URL":"ceskavec.com", "SOURCE":"1"},
        {"ID":"391", "URL":"desitka.org", "SOURCE":"1"},
        {"ID":"392", "URL":"badatelia.com", "SOURCE":"1"},
        {"ID":"393", "URL":"obcansky-tydenik.cz", "SOURCE":"1"},
        {"ID":"394", "URL":"cbreurope.sk", "SOURCE":"1"},
        {"ID":"395", "URL":"faktyadokazy.cc", "SOURCE":"1"},
        {"ID":"396", "URL":"dennik-dnes.sk", "SOURCE":"1"},
        {"ID":"397", "URL":"reformy.cz", "SOURCE":"1"},
        {"ID":"398", "URL":"elektrosmog.voxo.eu", "SOURCE":"1"},
        {"ID":"399", "URL":"meapatria.sk", "SOURCE":"1"},
        {"ID":"400", "URL":"kupredudominulosti.cz", "SOURCE":"1"},
        {"ID":"401", "URL":"mimoriadnespravy.sk", "SOURCE":"1"},
        {"ID":"402", "URL":"halonoviny.cz", "SOURCE":"1"},
        {"ID":"403", "URL":"megazpravy.cz", "SOURCE":"9"},
        {"ID":"404", "URL":"drsne.eu", "SOURCE":"1"}

    ];

    static sources =  [
            {"SOURCE":"1","NAME":"konspiratori.sk","URL":"https:\/\/www.konspiratori.sk\/zoznam-stranok.php"},
            {"SOURCE":"2","NAME":"evropskehodnoty.cz","URL":"https:\/\/www.evropskehodnoty.cz\/fungovani-ceskych-dezinformacnich-webu\/fungovani-ceskych-dezinformacnich-webu-2\/"},
            {"SOURCE":"3","NAME":"echo24.cz","URL":"https:\/\/echo24.cz\/a\/isYwV\/42-ceskych-a-slovenskych-webu-ktere-siri-ruske-lzi"},
            {"SOURCE":"4","NAME":"neovlivni.cz","URL":"https:\/\/neovlivni.cz\/vnitro-ma-databazi-dezinformacnich-webu-koho-na-ni-zaradilo\/"},
            {"SOURCE":"5","NAME":"respekt.cz","URL":"https:\/\/www.respekt.cz\/special\/2017\/dezinformace\/ceske-dezinformacni-weby"},
            {"SOURCE":"6","NAME":"ireporter.cz","URL":"https:\/\/www.ireporter.cz\/2020\/01\/15\/seznam-dezinformacnich-webu-posledni-znama-verze\/"},
            {"SOURCE":"8","NAME":"manipulatori.cz","URL":"https:\/\/manipulatori.cz\/mimoradny-report-odstraneni-konevovy-sochy\/"},
            {"SOURCE":"9","NAME":"manipulatori.cz","URL":"https:\/\/manipulatori.cz\/na-internetu-vznika-novy-dezinformacni-web-megazpravy-cz-produkuje-nekolik-dezinformaci-za-den\/"}
    ];

    static untrustedFacebookPages = [
    {"ID":"1","URL":"SputnikNews","SiteID":"172"},
    {"ID":"2","URL":"AC24.cz","SiteID":"1"},
    {"ID":"3","URL":"parlamentnilisty.cz","SiteID":"130"},
    {"ID":"4","URL":"casopisargument","SiteID":"31"},
    {"ID":"5","URL":"SifraCasopis","SiteID":"30"},
    {"ID":"6","URL":"aeronet.cz","SiteID":"2"},
    {"ID":"7","URL":"Afinabulblogcz","SiteID":"3"},
    {"ID":"8","URL":"AlternativniMagazin","SiteID":"6"},
    {"ID":"9","URL":"bajecnezeny","SiteID":"17"},
    {"ID":"10","URL":"bajecnylekar","SiteID":"19"},
    {"ID":"11","URL":"B%C3%A1je%C4%8Dn%C3%BD-l%C3%A9ka%C5%99-1904503426440012","SiteID":"18"},
    {"ID":"12","URL":"bajecnyzivot","SiteID":"20"},
    {"ID":"13","URL":"Breitbart","SiteID":"29"},
    {"ID":"14","URL":"ceskoaktualne","SiteID":"32"},
    {"ID":"15","URL":"ceskozdrave","SiteID":"33"},
    {"ID":"16","URL":"CestaCloveka","SiteID":"35"},
    {"ID":"17","URL":"cestyksobe","SiteID":"36"},
    {"ID":"18","URL":"cezokno","SiteID":"37"},
    {"ID":"19","URL":"conspicz","SiteID":"38"},
    {"ID":"20","URL":"czechfreepress","SiteID":"41"},
    {"ID":"21","URL":"datel.sk","SiteID":"42"},
    {"ID":"22","URL":"magazindavdva","SiteID":"43"},
    {"ID":"23","URL":"dennikpolitika","SiteID":"44"},
    {"ID":"24","URL":"dolezite.sk","SiteID":"47"},
    {"ID":"25","URL":"Dom%C3%A1ca-lie%C4%8Dba-1555211248131311","SiteID":"48"},
    {"ID":"26","URL":"www.drsne.sk","SiteID":"49"},
    {"ID":"27","URL":"eRepublika.cz","SiteID":"51"},
    {"ID":"28","URL":"eodborar.cz","SiteID":"54"},
    {"ID":"29","URL":"eportal.cz","SiteID":"55"},
    {"ID":"30","URL":"eurabia.cz","SiteID":"57"},
    {"ID":"31","URL":"Eurasia24-445786142269165","SiteID":"58"},
    {"ID":"32","URL":"EuroAsie.Info","SiteID":"59"},
    {"ID":"33","URL":"eurodenik","SiteID":"60"},
    {"ID":"34","URL":"Euronovinyeu-136701907009141","SiteID":"61"},
    {"ID":"35","URL":"eurorespekt","SiteID":"62"},
    {"ID":"36","URL":"euserver.cz","SiteID":"64"},
    {"ID":"37","URL":"Exopolitika-377359218568","SiteID":"65"},
    {"ID":"38","URL":"extraplus.sk","SiteID":"66"},
    {"ID":"39","URL":"farmazdravi","SiteID":"67"},
    {"ID":"40","URL":"freeGlobecz-nov%C3%BD-sv%C4%9Btov%C3%BD-%C5%99%C3%A1d-135133549861997","SiteID":"69"},
    {"ID":"41","URL":"FreePub.cz","SiteID":"70"},
    {"ID":"42","URL":"GottesGloriaTV","SiteID":"72"},
    {"ID":"43","URL":"Halonoviny.cz","SiteID":"402"},
    {"ID":"44","URL":"www.hlavnespravy.sk","SiteID":"74"},
    {"ID":"45","URL":"hlavnydenniksk","SiteID":"75"},
    {"ID":"46","URL":"hrot.info","SiteID":"76"},
    {"ID":"47","URL":"IdemVolitsk-100867488208903","SiteID":"77"},
    {"ID":"48","URL":"infokuryr","SiteID":"79"},
    {"ID":"49","URL":"Infovojna","SiteID":"80"},
    {"ID":"50","URL":"infovojnayoutube","SiteID":"80"},
    {"ID":"51","URL":"ipribeh","SiteID":"82"},
    {"ID":"52","URL":"instory.cz","SiteID":"83"},
    {"ID":"53","URL":"lajkit.cz","SiteID":"87"},
    {"ID":"54","URL":"Legalizuj.to","SiteID":"88"},
    {"ID":"55","URL":"LifeNewsSK","SiteID":"90"},
    {"ID":"56","URL":"Lucas-Perny-212562708781059","SiteID":"91"},
    {"ID":"57","URL":"www.kulturblog.sk","SiteID":"93"},
    {"ID":"58","URL":"megazcz","SiteID":"403"},
    {"ID":"59","URL":"MIKan-Moravsk%C3%A1-Informa%C4%8Dn%C3%AD-Kancel%C3%A1%C5%99-219323014790545","SiteID":"100"},
    {"ID":"60","URL":"Moc-v%C4%9Bdom%C3%AD-333103003725172","SiteID":"101"},
    {"ID":"61","URL":"nadhlad.ponad.protiklady","SiteID":"103"},
    {"ID":"62","URL":"nadlani.org","SiteID":"104"},
    {"ID":"63","URL":"napalete.sk","SiteID":"105"},
    {"ID":"64","URL":"narodninoviny.cz","SiteID":"106"},
    {"ID":"65","URL":"nazorobcana","SiteID":"108"},
    {"ID":"66","URL":"Nejvicinfo","SiteID":"111"},
    {"ID":"67","URL":"Netky.sk","SiteID":"115"},
    {"ID":"68","URL":"Nezdravi","SiteID":"116"},
    {"ID":"69","URL":"Orgo-Net-na-FB-232171370242412","SiteID":"121"},
    {"ID":"70","URL":"osud.cz","SiteID":"122"},
    {"ID":"71","URL":"OutsiderMedia-679074085513244","SiteID":"125"},
    {"ID":"72","URL":"panobcan.sk","SiteID":"127"},
    {"ID":"73","URL":"picuscapital","SiteID":"131"},
    {"ID":"74","URL":"Prav%C3%BD-prostor-zpravodajstv%C3%AD-bez-cenzury-406928900393","SiteID":"136"},
    {"ID":"75","URL":"precitajsi","SiteID":"137"},
    {"ID":"76","URL":"prehladsprav.sk","SiteID":"138"},
    {"ID":"77","URL":"Priezor","SiteID":"140"},
    {"ID":"78","URL":"PRIZNAKYTRANSFORMACE","SiteID":"141"},
    {"ID":"79","URL":"procproto","SiteID":"142"},
    {"ID":"80","URL":"proevropu","SiteID":"143"},
    {"ID":"81","URL":"ProSvet.cz","SiteID":"144"},
    {"ID":"82","URL":"protiproud.cz","SiteID":"145"},
    {"ID":"83","URL":"protiprudu.org","SiteID":"147"},
    {"ID":"84","URL":"prvnizpravy.cz","SiteID":"148"},
    {"ID":"85","URL":"radynadzlato.sk","SiteID":"151"},
    {"ID":"86","URL":"Rady-pre-Zdravie-447869788918538","SiteID":"152"},
    {"ID":"87","URL":"Rady-pre-%C5%BDENY-1596351360689861","SiteID":"153"},
    {"ID":"88","URL":"radyzdravie","SiteID":"154"},
    {"ID":"89","URL":"resso.sk","SiteID":"155"},
    {"ID":"90","URL":"Rukojmicz-113066090412619","SiteID":"159"},
    {"ID":"91","URL":"Sila-vedomia-1751679901760595","SiteID":"161"},
    {"ID":"92","URL":"skrytapravda","SiteID":"162"},
    {"ID":"93","URL":"sloboda.v.ockovani","SiteID":"163"},
    {"ID":"94","URL":"slobodnyvyber","SiteID":"164"},
    {"ID":"95","URL":"slobodny.vysielac.archiv.informacnej.vojny","SiteID":"165"},
    {"ID":"96","URL":"BEZ-CENZ%C3%9ARY-Slobodn%C3%BD-vysiela%C4%8D-1541976472741828","SiteID":"165"},
    {"ID":"97","URL":"smartnews.cz","SiteID":"169"},
    {"ID":"98","URL":"Spravodaj-105068854294049","SiteID":"170"},
    {"ID":"99","URL":"cz.sputnik","SiteID":"172"},
    {"ID":"100","URL":"SueneeUniverse","SiteID":"176"},
    {"ID":"101","URL":"svetkolemnas.info","SiteID":"177"},
    {"ID":"102","URL":"svobodnenovinyeu-240233692807752","SiteID":"178"},
    {"ID":"103","URL":"V%C4%9Bk-Sv%C4%9Btla-1781861465420457","SiteID":"181"},
    {"ID":"104","URL":"realvigilantcitizen","SiteID":"183"},
    {"ID":"105","URL":"vinegret.cz","SiteID":"184"},
    {"ID":"106","URL":"VIP-Noviny-1689437901275848","SiteID":"185"},
    {"ID":"107","URL":"VoxVictimscom-255214831194","SiteID":"189"},
    {"ID":"108","URL":"zastavme.autogenocidu","SiteID":"195"},
    {"ID":"109","URL":"stredoevropan","SiteID":"196"},
    {"ID":"110","URL":"tadesco.org","SiteID":"198"},
    {"ID":"111","URL":"TheMindUnleashed","SiteID":"200"},
    {"ID":"112","URL":"trendweb.sk","SiteID":"201"},
    {"ID":"113","URL":"citajteVedomec","SiteID":"203"},
    {"ID":"114","URL":"vitalitis.cz","SiteID":"204"},
    {"ID":"115","URL":"voxpopuliblog.cz","SiteID":"205"},
    {"ID":"116","URL":"Vylectesecz-1729514577374304","SiteID":"206"},
    {"ID":"117","URL":"WertyzReport","SiteID":"207"},
    {"ID":"118","URL":"wmmagazin.cz","SiteID":"208"},
    {"ID":"119","URL":"withform","SiteID":"211"},
    {"ID":"120","URL":"yournewswire","SiteID":"212"},
    {"ID":"121","URL":"ZahadnySvetsk-941539595978322","SiteID":"213"},
    {"ID":"122","URL":"MimoriadneSpravy","SiteID":"401"},
    {"ID":"123","URL":"kupredudominulosti","SiteID":"400"},
    {"ID":"124","URL":"meapatrianz","SiteID":"399"},
    {"ID":"125","URL":"klub.reformy.cz","SiteID":"397"},
    {"ID":"126","URL":"faktyadokazy","SiteID":"395"},
    {"ID":"127","URL":"naseveru.media","SiteID":"388"},
    {"ID":"128","URL":"youth.time.international.movement","SiteID":"381"}
    ];
}